# **Project** - **The DataViz Challenge-Transforming EDA Projects to Dashboards**

# **Problem Statement:**

In the context of Airbnb operations, how can the utilisation of Tableau Desktop/Tableau Public/PowerBI facilitate a comprehensive comparative examination between Chicago and New Orleans, two diverse urban environments?

This inquiry seeks to leverage Tableau Desktop/Tableau Public/PowerBI's visual analytics capabilities to uncover and illustrate the shared attributes, disparities, and distinctive patterns inherent to Airbnb's presence in these cities, thus elevating the depth and insightfulness of the study.


Airbnb, Inc. is an American company that operates an online marketplace for lodging, primarily homestays for vacation rentals, and tourism activities. Based in San Francisco, California, the platform is accessible via website and mobile app. Since 2008, guests and hosts have used Airbnb to expand on traveling possibilities and present a more unique, personalized way of experiencing the world. Today, Airbnb became one of a kind service that is used and recognized by the whole world. Data analysis on millions of listings provided through Airbnb is a crucial factor for the company. These millions of listings generate a lot of data - data that can be analyzed and used for security, business decisions, understanding of customers' and providers' (hosts) behavior and performance on the platform, guiding marketing initiatives, implementation of innovative additional services and much more.

# **Dataset Selection:**

For this EDA project, we have chosen the "Airbnb Listings Data" dataset from 2 major cities: Chicago and New Orleans. This dataset provides a comprehensive snapshot of various attributes related to Airbnb listings, such as property type, neighbourhood, pricing, availability, and more. The dataset is ideal for conducting an in-depth exploration of the local Airbnb market and deriving actionable insights.

**Dataset used :** [Chicago dataset](https://drive.google.com/file/d/1mTbU567RCvzBnP2lnfI60MU9W4VT7tkS/view?usp=sharing) and [New_Orleans dataset](https://drive.google.com/file/d/147VI7xUmYWs-RMOF9LPM6bGW0aFwEXly/view?usp=sharing)

# **Key Attributes:**

1. id: Unique identifier for each listing.

2. name: The title or name of the listing.

3. host_id: Unique identifier for the host of the property.

4. host_name: Name of the host.

5. neighbourhood_group: The broader area or group that the neighbourhood belongs to.

6. neighbourhood: Specific neighbourhood where the property is located.

7. latitude: Latitude coordinate of the property.

8. longitude: Longitude coordinate of the property.

9. room_type: Type of room (e.g., Private room, Entire home/apt, Shared room).

10. price: Price of the listing per night.

11. minimum_nights: Minimum number of nights required for booking.

12. number_of_reviews: Total number of reviews received for the listing.

13. last_review: Date of the last review.

14. reviews_per_month: Average number of reviews per month.

15. availability_365: Number of days the listing is available for booking in a year.

# **know your data:**

### Import Libraries

In [ ]:
# Import Libraries
import numpy as np
import pandas as pd
from google.colab import files

# Upload file from local to colab
uploaded = files.upload()

Saving listings_airbnb_chicago.csv to listings_airbnb_chicago.csv
Saving listings_airbnb_New_Orleans.csv to listings_airbnb_New_Orleans.csv

In [ ]:
# Load both Dataset
chicago = pd.read_csv("listings_airbnb_chicago.csv")
new_orleans = pd.read_csv("listings_airbnb_New_Orleans.csv")

In [ ]:
# chicago Dataset First Look
chicago.head(2)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,2384,Hyde Park - Walk to University of Chicago,2613,Rebecca,NaN,Hyde Park,41.78790,-87.58780,Private room,125.0,3,250,2024-10-14,2.02,1,343,16,R17000015609
1,7126,Tiny Studio Apartment 94 Walk Score,17928,Sarah,NaN,West Town,41.90166,-87.68021,Entire home/apt,81.0,2,569,2025-02-09,2.98,1,275,53,R24000114046

In [ ]:
# new orleans Dataset First Look
new_orleans.head(2)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365,number_of_reviews_ltm,license
0,19091,Fully Furnished Cozy Apartment,72880,John,NaN,Leonidas,29.96100,-90.11950,Entire home/apt,61.0,30,503,2023-11-06,2.78,1,329,0,"22-RSTR-14107, 22-OSTR-14105"
1,71624,Ravenwood Manor (Historic Bywater),367223,Susan,NaN,Bywater,29.96153,-90.04364,Entire home/apt,167.0,30,313,2025-02-02,1.83,1,342,15,"21-RSTR-18609, 22-OSTR-20720"

In [ ]:
# adding city column here in both datasets
chicago["City"]="Chicago"
new_orleans["City"]="New_Orleans"

In [ ]:
# merge both datasets
chicago_and_Orlean = pd.concat([chicago, new_orleans], ignore_index=True)

In [ ]:
# Clean Dataset Rows & Columns count
num_rows_chi, num_columns_chi = chicago_and_Orlean.shape
print(f"chicago_and_Orlean - Number of rows: {num_rows_chi}")
print(f"chicago_and_Orlean - Number of columns: {num_columns_chi}")

chicago_and_Orlean - Number of rows: 16590
chicago_and_Orlean - Number of columns: 19

In [ ]:
# Dataset Info
chicago_and_Orlean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16590 entries, 0 to 16589
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              16590 non-null  int64
 1   name                            16590 non-null  object
 2   host_id                         16590 non-null  int64
 3   host_name                       16577 non-null  object
 4   neighbourhood_group             0 non-null      float64
 5   neighbourhood                   16590 non-null  object
 6   latitude                        16590 non-null  float64
 7   longitude                       16590 non-null  float64
 8   room_type                       16590 non-null  object
 9   price                           14358 non-null  float64
 10  minimum_nights                  16590 non-null  int64
 11  number_of_reviews               16590 non-null  int64
 12  last_review                     13384 non-null  object
 13  reviews_per_month               13384 non-null  float64
 14  calculated_host_listings_count  16590 non-null  int64
 15  availability_365                16590 non-null  int64
 16  number_of_reviews_ltm           16590 non-null  int64
 17  license                         13338 non-null  object
 18  City                            16590 non-null  object
dtypes: float64(5), int64(7), object(7)
memory usage: 2.4+ MB

In [ ]:
# checking duplicates here if any
duplicate_count = chicago_and_Orlean.duplicated().sum()
print(f"Number of duplicate rows: {duplicate_count}")

Number of duplicate rows: 0

In [ ]:
# Missing Values/Null Values Count
missing_values = chicago_and_Orlean.isnull().sum()
print("Missing values per column :")
print(missing_values)

Missing values per column :
id                                    0
name                                  0
host_id                               0
host_name                            13
neighbourhood_group               16590
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                              2232
minimum_nights                        0
number_of_reviews                     0
last_review                        3206
reviews_per_month                  3206
calculated_host_listings_count        0
availability_365                      0
number_of_reviews_ltm                 0
license                            3252
City                                  0
dtype: int64

# About the Dataset

**Dataset Overview**

* The dataset used in this project is the Airbnb Listings Data for two major cities: Chicago and New Orleans. Each dataset contains detailed information about Airbnb properties, including location, pricing, availability, and host details.

* After combining both datasets, we created a unified dataset (chicago_and_Orlean) to perform comparative analysis between the two cities.

**Key Features of the Dataset**

* Total Rows & Columns: The dataset contains multiple listings with 19 attributes related to Airbnb properties.

* City Column: A new column City is added to distinguish between Chicago and New Orleans listings.

* Unique Listings: Each row represents a unique Airbnb listing identified by id.

* The dataset contains missing values in some columns such as reviews_per_month, last_review, and host_name.

* There are no duplicate records in the dataset.

* Some columns like neighbourhood_group and license may not be useful for analysis.

# **Data cleaning and transformation:**

In [ ]:
# Drop unnecessary columns
chicago_and_Orlean.drop(['neighbourhood_group', 'license'], axis=1, inplace=True, errors='ignore')

In [ ]:
# Remove rows where price is missing
chicago_and_Orlean.dropna(subset=['price'], inplace=True)

In [ ]:
# Fill missing host_name with most frequent value
chicago_and_Orlean['host_name'] = chicago_and_Orlean['host_name'].fillna(chicago_and_Orlean['host_name'].mode()[0])

In [ ]:
# Convert last_review to datetime
chicago_and_Orlean['last_review'] = pd.to_datetime(chicago_and_Orlean['last_review'], errors='coerce')

In [ ]:
# Fill missing last_review with median date
chicago_and_Orlean['last_review'] = chicago_and_Orlean['last_review'].fillna(chicago_and_Orlean['last_review'].median())

In [ ]:
# Fill missing reviews_per_month with mean
chicago_and_Orlean['reviews_per_month'] = chicago_and_Orlean['reviews_per_month'].fillna(chicago_and_Orlean['reviews_per_month'].mean())

In [ ]:
print("\nMissing values after cleaning:")
print(chicago_and_Orlean.isnull().sum())

Missing values after cleaning:
id                                0
name                              0
host_id                           0
host_name                         0
neighbourhood                     0
latitude                          0
longitude                         0
room_type                         0
price                             0
minimum_nights                    0
number_of_reviews                 0
last_review                       0
reviews_per_month                 0
calculated_host_listings_count    0
availability_365                  0
number_of_reviews_ltm             0
City                              0
dtype: int64

In [ ]:
print("\nUpdated Dataset Info:")
chicago_and_Orlean.info()

Updated Dataset Info:
<class 'pandas.core.frame.DataFrame'>
Index: 14358 entries, 0 to 16589
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              14358 non-null  int64
 1   name                            14358 non-null  object
 2   host_id                         14358 non-null  int64
 3   host_name                       14358 non-null  object
 4   neighbourhood                   14358 non-null  object
 5   latitude                        14358 non-null  float64
 6   longitude                       14358 non-null  float64
 7   room_type                       14358 non-null  object
 8   price                           14358 non-null  float64
 9   minimum_nights                  14358 non-null  int64
 10  number_of_reviews               14358 non-null  int64
 11  last_review                     14358 non-null  datetime64[ns]
 12  reviews_per_month               14358 non-null  float64
 13  calculated_host_listings_count  14358 non-null  int64
 14  availability_365                14358 non-null  int64
 15  number_of_reviews_ltm           14358 non-null  int64
 16  City                            14358 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(7), object(5)
memory usage: 2.0+ MB

In [ ]:
chicago_and_Orlean.to_csv("chicago_and_Orlean.csv", index=False)

In [ ]:
# Download file in Colab
files.download("chicago_and_Orlean.csv")

print("\n Data Cleaning Completed & File Downloaded")

 Data Cleaning Completed & File Downloaded

# Data Cleaning and Transformation briefing

* **Column Optimization:**
Irrelevant and redundant columns such as neighbourhood_group and license were removed to streamline the dataset and focus on meaningful analytical features.

* **Handling Missing Values** :
Rows with missing price values were removed, as price is a key variable for analysis and visualization.

* **Categorical Data Imputation:**
Missing values in the host_name column were filled using the most frequent (mode) value to maintain consistency in host-related analysis.

* **Date Processing and Imputation:**
The last_review column was converted into a datetime format. Missing values were then imputed using the median date to preserve temporal continuity without introducing bias.

* **Numerical Data Imputation:**
Missing values in reviews_per_month were replaced with the mean value to ensure completeness while maintaining overall data distribution.

**Link of the Dashboard built on PowerBI :** [PowerBI Dashboard](https://drive.google.com/file/d/1v2crD2AC-0fGZetwk8Yq7laPfH_Lv2QW/view?usp=sharing)

**Link of github :** [Github Repository](https://github.com/Prajwalx8/The-DataViz-Challenge-Airbnb_Data_PowerBI_Dashboard)